# Generated by Django 3.2.2 on 2021-05-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('request_type', models.CharField(max_length=500)),
                ('application', models.CharField(max_length=500)),
                ('windows_id', models.CharField(max_length=200)),
                ('current_branch', models.CharField(max_length=500)),
                ('current_role', models.CharField(max_length=300)),
                ('line_manager', models.CharField(max_length=200)),
                ('approved_by_line_manager', models.BooleanField(default=False)),
                ('zonal', models.CharField(max_length=200)),
                ('approved_by_zonal', models.BooleanField(default=False)),
                ('approved_by_internal_control', models.BooleanField(default=False)),
                ('request_status', models.CharField(default='New', max_length=200)),
                ('requester_comment', models.CharField(max_length=200000)),
                ('zonal_comment', models.CharField(max_length=200000)),
                ('line_manager_comment', models.CharField(max_length=200000)),
                ('internal_control_comment', models.CharField(max_length=200000)),
                ('date_approved_by_zonal', models.DateTimeField()),
                ('date_approved_by_line_manager', models.DateTimeField()),
                ('date_modified_by_internal_control', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
